// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetPaginationFriendsReq {
    #[prost(message, optional, tag="1")]
    pub pagination: ::core::option::Option<super::sdkws::RequestPagination>,
    #[prost(string, tag="2")]
    pub user_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetPaginationFriendsResp {
    #[prost(message, repeated, tag="1")]
    pub friends_info: ::prost::alloc::vec::Vec<super::sdkws::FriendInfo>,
    #[prost(int32, tag="2")]
    pub total: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ApplyToAddFriendReq {
    #[prost(string, tag="1")]
    pub from_user_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub to_user_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub req_msg: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub ex: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ApplyToAddFriendResp {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FriendInfo {
    #[prost(string, tag="1")]
    pub owner_user_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub friend_user_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub friend_nickname: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub friend_face_url: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub remark: ::prost::alloc::string::String,
    #[prost(int64, tag="6")]
    pub create_time: i64,
    #[prost(int32, tag="7")]
    pub add_source: i32,
    #[prost(string, tag="8")]
    pub operator_user_id: ::prost::alloc::string::String,
    #[prost(string, tag="9")]
    pub ex: ::prost::alloc::string::String,
    #[prost(bool, tag="10")]
    pub is_pinned: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ImportFriendReq {
    #[prost(string, tag="1")]
    pub owner_user_id: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="2")]
    pub friend_user_i_ds: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ImportFriendResp {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetPaginationFriendsApplyToReq {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag="2")]
    pub pagination: ::core::option::Option<super::sdkws::RequestPagination>,
    #[prost(int32, repeated, tag="3")]
    pub handle_results: ::prost::alloc::vec::Vec<i32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetPaginationFriendsApplyToResp {
    #[prost(message, repeated, tag="1")]
    pub friend_requests: ::prost::alloc::vec::Vec<super::sdkws::FriendRequest>,
    #[prost(int32, tag="2")]
    pub total: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetDesignatedFriendsApplyReq {
    #[prost(string, tag="1")]
    pub from_user_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub to_user_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetDesignatedFriendsApplyResp {
    #[prost(message, repeated, tag="1")]
    pub friend_requests: ::prost::alloc::vec::Vec<super::sdkws::FriendRequest>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetSelfUnhandledApplyCountReq {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(int64, tag="2")]
    pub time: i64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetSelfUnhandledApplyCountResp {
    #[prost(int64, tag="1")]
    pub count: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetIncrementalFriendsApplyToReq {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub version_id: ::prost::alloc::string::String,
    #[prost(uint64, tag="3")]
    pub version: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetIncrementalFriendsApplyToResp {
    #[prost(uint64, tag="1")]
    pub version: u64,
    #[prost(string, tag="2")]
    pub version_id: ::prost::alloc::string::String,
    #[prost(bool, tag="3")]
    pub full: bool,
    #[prost(string, repeated, tag="4")]
    pub delete_user_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, repeated, tag="5")]
    pub changes: ::prost::alloc::vec::Vec<super::sdkws::FriendRequest>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetIncrementalFriendsApplyFromReq {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub version_id: ::prost::alloc::string::String,
    #[prost(uint64, tag="3")]
    pub version: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetIncrementalFriendsApplyFromResp {
    #[prost(uint64, tag="1")]
    pub version: u64,
    #[prost(string, tag="2")]
    pub version_id: ::prost::alloc::string::String,
    #[prost(bool, tag="3")]
    pub full: bool,
    #[prost(string, repeated, tag="4")]
    pub delete_user_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, repeated, tag="5")]
    pub changes: ::prost::alloc::vec::Vec<super::sdkws::FriendRequest>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetDesignatedFriendsReq {
    #[prost(string, tag="1")]
    pub owner_user_id: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="2")]
    pub friend_user_i_ds: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetDesignatedFriendsResp {
    #[prost(message, repeated, tag="1")]
    pub friends_info: ::prost::alloc::vec::Vec<super::sdkws::FriendInfo>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AddBlackReq {
    #[prost(string, tag="1")]
    pub owner_user_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub black_user_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub ex: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct AddBlackResp {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RemoveBlackReq {
    #[prost(string, tag="1")]
    pub owner_user_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub black_user_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct RemoveBlackResp {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetPaginationBlacksReq {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag="2")]
    pub pagination: ::core::option::Option<super::sdkws::RequestPagination>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetPaginationBlacksResp {
    #[prost(message, repeated, tag="1")]
    pub blacks: ::prost::alloc::vec::Vec<super::sdkws::BlackInfo>,
    #[prost(int32, tag="2")]
    pub total: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IsFriendReq {
    #[prost(string, tag="1")]
    pub user_id1: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub user_id2: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct IsFriendResp {
    /// If userID2 is in userID1’s friend list, return true
    #[prost(bool, tag="1")]
    pub in_user1_friends: bool,
    /// If userID1 is in userID2’s friend list, return true
    #[prost(bool, tag="2")]
    pub in_user2_friends: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IsBlackReq {
    #[prost(string, tag="1")]
    pub user_id1: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub user_id2: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct IsBlackResp {
    /// If userID2 is in userID1's blacklist, true
    #[prost(bool, tag="1")]
    pub in_user1_blacks: bool,
    /// If userID1 is in userID2's blacklist, true
    #[prost(bool, tag="2")]
    pub in_user2_blacks: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeleteFriendReq {
    #[prost(string, tag="1")]
    pub owner_user_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub friend_user_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct DeleteFriendResp {
}
/// process
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RespondFriendApplyReq {
    /// ID of the user initiating the friend request
    #[prost(string, tag="1")]
    pub from_user_id: ::prost::alloc::string::String,
    /// ID of the user receiving the friend request
    #[prost(string, tag="2")]
    pub to_user_id: ::prost::alloc::string::String,
    #[prost(int32, tag="3")]
    pub handle_result: i32,
    #[prost(string, tag="4")]
    pub handle_msg: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct RespondFriendApplyResp {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateFriendsReq {
    #[prost(string, tag="1")]
    pub owner_user_id: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="2")]
    pub friend_user_i_ds: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, optional, tag="3")]
    pub is_pinned: ::core::option::Option<super::protobuf::BoolValue>,
    #[prost(message, optional, tag="4")]
    pub remark: ::core::option::Option<super::protobuf::StringValue>,
    #[prost(message, optional, tag="5")]
    pub ex: ::core::option::Option<super::protobuf::StringValue>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct UpdateFriendsResp {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetFriendRemarkReq {
    #[prost(string, tag="1")]
    pub owner_user_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub friend_user_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub remark: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SetFriendRemarkResp {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetPaginationFriendsApplyFromReq {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag="2")]
    pub pagination: ::core::option::Option<super::sdkws::RequestPagination>,
    #[prost(int32, repeated, tag="3")]
    pub handle_results: ::prost::alloc::vec::Vec<i32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetPaginationFriendsApplyFromResp {
    #[prost(message, repeated, tag="1")]
    pub friend_requests: ::prost::alloc::vec::Vec<super::sdkws::FriendRequest>,
    #[prost(int32, tag="2")]
    pub total: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetFriendIDsReq {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetFriendIDsResp {
    #[prost(string, repeated, tag="1")]
    pub friend_i_ds: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetSpecifiedFriendsInfoReq {
    #[prost(string, tag="1")]
    pub owner_user_id: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="2")]
    pub user_id_list: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetSpecifiedFriendsInfoInfo {
    #[prost(message, optional, tag="1")]
    pub user_info: ::core::option::Option<super::sdkws::UserInfo>,
    #[prost(message, optional, tag="2")]
    pub friend_info: ::core::option::Option<super::sdkws::FriendInfo>,
    #[prost(message, optional, tag="3")]
    pub black_info: ::core::option::Option<super::sdkws::BlackInfo>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetSpecifiedFriendsInfoResp {
    #[prost(message, repeated, tag="1")]
    pub infos: ::prost::alloc::vec::Vec<GetSpecifiedFriendsInfoInfo>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetIncrementalFriendsReq {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub version_id: ::prost::alloc::string::String,
    #[prost(uint64, tag="3")]
    pub version: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetIncrementalFriendsResp {
    #[prost(uint64, tag="1")]
    pub version: u64,
    #[prost(string, tag="2")]
    pub version_id: ::prost::alloc::string::String,
    #[prost(bool, tag="3")]
    pub full: bool,
    #[prost(string, repeated, tag="4")]
    pub delete: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, repeated, tag="5")]
    pub insert: ::prost::alloc::vec::Vec<super::sdkws::FriendInfo>,
    #[prost(message, repeated, tag="6")]
    pub update: ::prost::alloc::vec::Vec<super::sdkws::FriendInfo>,
    #[prost(uint64, tag="7")]
    pub sort_version: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetIncrementalBlacksReq {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub version_id: ::prost::alloc::string::String,
    #[prost(uint64, tag="3")]
    pub version: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetIncrementalBlacksResp {
    #[prost(uint64, tag="1")]
    pub version: u64,
    #[prost(string, tag="2")]
    pub version_id: ::prost::alloc::string::String,
    #[prost(bool, tag="3")]
    pub full: bool,
    #[prost(string, repeated, tag="4")]
    pub delete: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, repeated, tag="5")]
    pub insert: ::prost::alloc::vec::Vec<super::sdkws::BlackInfo>,
    #[prost(message, repeated, tag="6")]
    pub update: ::prost::alloc::vec::Vec<super::sdkws::BlackInfo>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetSpecifiedBlacksReq {
    #[prost(string, tag="1")]
    pub owner_user_id: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="2")]
    pub user_id_list: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetSpecifiedBlacksResp {
    #[prost(message, repeated, tag="1")]
    pub blacks: ::prost::alloc::vec::Vec<super::sdkws::BlackInfo>,
    #[prost(int32, tag="2")]
    pub total: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetFullFriendUserIDsReq {
    #[prost(uint64, tag="1")]
    pub id_hash: u64,
    #[prost(string, tag="2")]
    pub user_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetFullFriendUserIDsResp {
    #[prost(uint64, tag="1")]
    pub version: u64,
    #[prost(string, tag="2")]
    pub version_id: ::prost::alloc::string::String,
    #[prost(bool, tag="3")]
    pub equal: bool,
    #[prost(string, repeated, tag="4")]
    pub user_i_ds: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NotificationUserInfoUpdateReq {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag="2")]
    pub old_user_info: ::core::option::Option<super::sdkws::UserInfo>,
    #[prost(message, optional, tag="3")]
    pub new_user_info: ::core::option::Option<super::sdkws::UserInfo>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct NotificationUserInfoUpdateResp {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FriendInfoOnly {
    #[prost(string, tag="1")]
    pub owner_user_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub friend_user_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub remark: ::prost::alloc::string::String,
    #[prost(int64, tag="4")]
    pub create_time: i64,
    #[prost(int32, tag="5")]
    pub add_source: i32,
    #[prost(string, tag="6")]
    pub operator_user_id: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub ex: ::prost::alloc::string::String,
    #[prost(bool, tag="8")]
    pub is_pinned: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetFriendInfoReq {
    #[prost(string, tag="1")]
    pub owner_user_id: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="2")]
    pub friend_user_i_ds: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetFriendInfoResp {
    #[prost(message, repeated, tag="1")]
    pub friend_infos: ::prost::alloc::vec::Vec<FriendInfoOnly>,
}
// @@protoc_insertion_point(module)
