// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgDataToMq {
    #[prost(string, tag="1")]
    pub token: ::prost::alloc::string::String,
    #[prost(message, optional, tag="2")]
    pub msg_data: ::core::option::Option<super::sdkws::MsgData>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgDataToDb {
    #[prost(message, optional, tag="1")]
    pub msg_data: ::core::option::Option<super::sdkws::MsgData>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PushMsgDataToMq {
    #[prost(message, optional, tag="1")]
    pub msg_data: ::core::option::Option<super::sdkws::MsgData>,
    #[prost(string, tag="2")]
    pub conversation_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgDataToMongoByMq {
    #[prost(int64, tag="1")]
    pub last_seq: i64,
    #[prost(string, tag="2")]
    pub conversation_id: ::prost::alloc::string::String,
    #[prost(message, repeated, tag="3")]
    pub msg_data: ::prost::alloc::vec::Vec<super::sdkws::MsgData>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetMaxAndMinSeqReq {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetMaxAndMinSeqResp {
    #[prost(int64, tag="1")]
    pub max_seq: i64,
    #[prost(int64, tag="2")]
    pub min_seq: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SendMsgReq {
    #[prost(message, optional, tag="3")]
    pub msg_data: ::core::option::Option<super::sdkws::MsgData>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SendMsgResp {
    #[prost(string, tag="1")]
    pub server_msg_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub client_msg_id: ::prost::alloc::string::String,
    #[prost(int64, tag="3")]
    pub send_time: i64,
    #[prost(message, optional, tag="4")]
    pub modify: ::core::option::Option<super::sdkws::MsgData>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SendSimpleMsgReq {
    #[prost(message, optional, tag="3")]
    pub msg_data: ::core::option::Option<super::sdkws::MsgData>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SendSimpleMsgResp {
    #[prost(string, tag="1")]
    pub server_msg_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub client_msg_id: ::prost::alloc::string::String,
    #[prost(int64, tag="3")]
    pub send_time: i64,
    #[prost(message, optional, tag="4")]
    pub modify: ::core::option::Option<super::sdkws::MsgData>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SetSendMsgStatusReq {
    #[prost(int32, tag="1")]
    pub status: i32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SetSendMsgStatusResp {
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetSendMsgStatusReq {
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetSendMsgStatusResp {
    #[prost(int32, tag="1")]
    pub status: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgDataToModifyByMq {
    #[prost(message, repeated, tag="1")]
    pub messages: ::prost::alloc::vec::Vec<super::sdkws::MsgData>,
    #[prost(string, tag="2")]
    pub conversation_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct DelMsgsReq {
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct DelMsgsResp {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RevokeMsgReq {
    #[prost(string, tag="1")]
    pub conversation_id: ::prost::alloc::string::String,
    #[prost(int64, tag="2")]
    pub seq: i64,
    #[prost(string, tag="3")]
    pub user_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct RevokeMsgResp {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MarkMsgsAsReadReq {
    #[prost(string, tag="1")]
    pub conversation_id: ::prost::alloc::string::String,
    #[prost(int64, repeated, tag="2")]
    pub seqs: ::prost::alloc::vec::Vec<i64>,
    #[prost(string, tag="3")]
    pub user_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MarkMsgsAsReadResp {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MarkConversationAsReadReq {
    #[prost(string, tag="1")]
    pub conversation_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(int64, tag="3")]
    pub has_read_seq: i64,
    #[prost(int64, repeated, tag="4")]
    pub seqs: ::prost::alloc::vec::Vec<i64>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MarkConversationAsReadResp {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetConversationHasReadSeqReq {
    #[prost(string, tag="1")]
    pub conversation_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(int64, tag="3")]
    pub has_read_seq: i64,
    #[prost(bool, tag="4")]
    pub no_notification: bool,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SetConversationHasReadSeqResp {
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct DeleteSyncOpt {
    #[prost(bool, tag="3")]
    pub is_sync_self: bool,
    #[prost(bool, tag="4")]
    pub is_sync_other: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClearConversationsMsgReq {
    #[prost(string, repeated, tag="1")]
    pub conversation_i_ds: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag="2")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag="3")]
    pub delete_sync_opt: ::core::option::Option<DeleteSyncOpt>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ClearConversationsMsgResp {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UserClearAllMsgReq {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag="3")]
    pub delete_sync_opt: ::core::option::Option<DeleteSyncOpt>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct UserClearAllMsgResp {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeleteMsgsReq {
    #[prost(string, tag="1")]
    pub conversation_id: ::prost::alloc::string::String,
    #[prost(int64, repeated, tag="2")]
    pub seqs: ::prost::alloc::vec::Vec<i64>,
    #[prost(string, tag="3")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag="4")]
    pub delete_sync_opt: ::core::option::Option<DeleteSyncOpt>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct DeleteMsgsResp {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeleteMsgPhysicalReq {
    #[prost(string, repeated, tag="1")]
    pub conversation_i_ds: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(int64, tag="2")]
    pub timestamp: i64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct DeleteMsgPhysicalResp {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeleteMsgPhysicalBySeqReq {
    #[prost(string, tag="1")]
    pub conversation_id: ::prost::alloc::string::String,
    #[prost(int64, repeated, tag="2")]
    pub seqs: ::prost::alloc::vec::Vec<i64>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct DeleteMsgPhysicalBySeqResp {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetMaxSeqsReq {
    #[prost(string, repeated, tag="1")]
    pub conversation_i_ds: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetHasReadSeqsReq {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="2")]
    pub conversation_i_ds: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SeqsInfoResp {
    #[prost(map="string, int64", tag="1")]
    pub max_seqs: ::std::collections::HashMap<::prost::alloc::string::String, i64>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetMsgByConversationIDsReq {
    #[prost(string, repeated, tag="1")]
    pub conversation_i_ds: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(map="string, int64", tag="2")]
    pub max_seqs: ::std::collections::HashMap<::prost::alloc::string::String, i64>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetMsgByConversationIDsResp {
    #[prost(map="string, message", tag="1")]
    pub msg_datas: ::std::collections::HashMap<::prost::alloc::string::String, super::sdkws::MsgData>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetConversationMaxSeqReq {
    #[prost(string, tag="1")]
    pub conversation_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetConversationMaxSeqResp {
    #[prost(int64, tag="1")]
    pub max_seq: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetConversationsHasReadAndMaxSeqReq {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="2")]
    pub conversation_i_ds: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(bool, tag="3")]
    pub return_pinned: bool,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Seqs {
    #[prost(int64, tag="1")]
    pub max_seq: i64,
    #[prost(int64, tag="2")]
    pub has_read_seq: i64,
    #[prost(int64, tag="3")]
    pub max_seq_time: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetConversationsHasReadAndMaxSeqResp {
    #[prost(map="string, message", tag="1")]
    pub seqs: ::std::collections::HashMap<::prost::alloc::string::String, Seqs>,
    #[prost(string, repeated, tag="2")]
    pub pinned_conversation_i_ds: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetActiveUserReq {
    #[prost(int64, tag="1")]
    pub start: i64,
    #[prost(int64, tag="2")]
    pub end: i64,
    #[prost(bool, tag="3")]
    pub ase: bool,
    #[prost(bool, tag="4")]
    pub group: bool,
    #[prost(message, optional, tag="5")]
    pub pagination: ::core::option::Option<super::sdkws::RequestPagination>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ActiveUser {
    #[prost(message, optional, tag="1")]
    pub user: ::core::option::Option<super::sdkws::UserInfo>,
    #[prost(int64, tag="2")]
    pub count: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetActiveUserResp {
    #[prost(int64, tag="1")]
    pub msg_count: i64,
    #[prost(int64, tag="2")]
    pub user_count: i64,
    #[prost(map="string, int64", tag="3")]
    pub date_count: ::std::collections::HashMap<::prost::alloc::string::String, i64>,
    #[prost(message, repeated, tag="4")]
    pub users: ::prost::alloc::vec::Vec<ActiveUser>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetActiveGroupReq {
    #[prost(int64, tag="1")]
    pub start: i64,
    #[prost(int64, tag="2")]
    pub end: i64,
    #[prost(bool, tag="3")]
    pub ase: bool,
    #[prost(message, optional, tag="4")]
    pub pagination: ::core::option::Option<super::sdkws::RequestPagination>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ActiveGroup {
    #[prost(message, optional, tag="1")]
    pub group: ::core::option::Option<super::sdkws::GroupInfo>,
    #[prost(int64, tag="2")]
    pub count: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetActiveGroupResp {
    #[prost(int64, tag="1")]
    pub msg_count: i64,
    #[prost(int64, tag="2")]
    pub group_count: i64,
    #[prost(map="string, int64", tag="3")]
    pub date_count: ::std::collections::HashMap<::prost::alloc::string::String, i64>,
    #[prost(message, repeated, tag="4")]
    pub groups: ::prost::alloc::vec::Vec<ActiveGroup>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SearchMessageReq {
    /// 发送者ID
    #[prost(string, tag="1")]
    pub send_id: ::prost::alloc::string::String,
    /// 接收者ID
    #[prost(string, tag="2")]
    pub recv_id: ::prost::alloc::string::String,
    #[prost(int32, tag="3")]
    pub content_type: i32,
    #[prost(string, tag="4")]
    pub send_time: ::prost::alloc::string::String,
    #[prost(int32, tag="5")]
    pub session_type: i32,
    #[prost(message, optional, tag="6")]
    pub pagination: ::core::option::Option<super::sdkws::RequestPagination>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SearchChatLog {
    #[prost(message, optional, tag="1")]
    pub chat_log: ::core::option::Option<ChatLog>,
    #[prost(bool, tag="2")]
    pub is_revoked: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SearchedMsgData {
    #[prost(message, optional, tag="1")]
    pub msg_data: ::core::option::Option<super::sdkws::MsgData>,
    #[prost(bool, tag="2")]
    pub is_revoked: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SearchMessageResp {
    #[prost(message, repeated, tag="1")]
    pub chat_logs: ::prost::alloc::vec::Vec<SearchChatLog>,
    #[prost(int32, tag="2")]
    pub chat_logs_num: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChatLog {
    #[prost(string, tag="1")]
    pub server_msg_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub client_msg_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub send_id: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub recv_id: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub group_id: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub recv_nickname: ::prost::alloc::string::String,
    #[prost(int32, tag="7")]
    pub sender_platform_id: i32,
    #[prost(string, tag="8")]
    pub sender_nickname: ::prost::alloc::string::String,
    #[prost(string, tag="9")]
    pub sender_face_url: ::prost::alloc::string::String,
    #[prost(string, tag="10")]
    pub group_name: ::prost::alloc::string::String,
    #[prost(int32, tag="11")]
    pub session_type: i32,
    #[prost(int32, tag="12")]
    pub msg_from: i32,
    #[prost(int32, tag="13")]
    pub content_type: i32,
    #[prost(string, tag="14")]
    pub content: ::prost::alloc::string::String,
    #[prost(int32, tag="15")]
    pub status: i32,
    #[prost(int64, tag="16")]
    pub send_time: i64,
    #[prost(int64, tag="17")]
    pub create_time: i64,
    #[prost(string, tag="18")]
    pub ex: ::prost::alloc::string::String,
    #[prost(string, tag="19")]
    pub group_face_url: ::prost::alloc::string::String,
    #[prost(uint32, tag="20")]
    pub group_member_count: u32,
    #[prost(int64, tag="21")]
    pub seq: i64,
    #[prost(string, tag="22")]
    pub group_owner: ::prost::alloc::string::String,
    #[prost(int32, tag="23")]
    pub group_type: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BatchSendMessageReq {
    #[prost(string, repeated, tag="1")]
    pub recv_id_list: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, optional, tag="2")]
    pub msg_data: ::core::option::Option<super::sdkws::MsgData>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct BatchSendMessageResp {
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetServerTimeReq {
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetServerTimeResp {
    #[prost(int64, tag="1")]
    pub server_time: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClearMsgReq {
    #[prost(message, repeated, tag="1")]
    pub conversations: ::prost::alloc::vec::Vec<super::conversation::Conversation>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ClearMsgResp {
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct DestructMsgsReq {
    #[prost(int64, tag="1")]
    pub timestamp: i64,
    #[prost(int32, tag="2")]
    pub limit: i32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct DestructMsgsResp {
    #[prost(int32, tag="1")]
    pub count: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetUserConversationsMinSeqReq {
    #[prost(string, repeated, tag="1")]
    pub user_i_ds: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag="2")]
    pub conversation_id: ::prost::alloc::string::String,
    #[prost(int64, tag="3")]
    pub seq: i64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SetUserConversationsMinSeqResp {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConversationSeqs {
    #[prost(string, tag="2")]
    pub conversation_id: ::prost::alloc::string::String,
    #[prost(int64, repeated, tag="3")]
    pub seqs: ::prost::alloc::vec::Vec<i64>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetSeqMessageReq {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(message, repeated, tag="2")]
    pub conversations: ::prost::alloc::vec::Vec<ConversationSeqs>,
    #[prost(enumeration="super::sdkws::PullOrder", tag="3")]
    pub order: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetSeqMessageResp {
    #[prost(map="string, message", tag="1")]
    pub msgs: ::std::collections::HashMap<::prost::alloc::string::String, super::sdkws::PullMsgs>,
    #[prost(map="string, message", tag="2")]
    pub notification_msgs: ::std::collections::HashMap<::prost::alloc::string::String, super::sdkws::PullMsgs>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetActiveConversationReq {
    #[prost(string, repeated, tag="1")]
    pub conversation_i_ds: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(int64, tag="2")]
    pub limit: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ActiveConversation {
    #[prost(string, tag="1")]
    pub conversation_id: ::prost::alloc::string::String,
    #[prost(int64, tag="2")]
    pub last_time: i64,
    #[prost(int64, tag="3")]
    pub max_seq: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetActiveConversationResp {
    #[prost(message, repeated, tag="1")]
    pub conversations: ::prost::alloc::vec::Vec<ActiveConversation>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetUserConversationMaxSeqReq {
    #[prost(string, tag="1")]
    pub conversation_id: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="2")]
    pub owner_user_id: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(int64, tag="3")]
    pub max_seq: i64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SetUserConversationMaxSeqResp {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetUserConversationMinSeqReq {
    #[prost(string, tag="1")]
    pub conversation_id: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="2")]
    pub owner_user_id: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(int64, tag="3")]
    pub min_seq: i64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SetUserConversationMinSeqResp {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetLastMessageSeqByTimeReq {
    #[prost(string, tag="1")]
    pub conversation_id: ::prost::alloc::string::String,
    #[prost(int64, tag="2")]
    pub time: i64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetLastMessageSeqByTimeResp {
    #[prost(int64, tag="1")]
    pub seq: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetLastMessageReq {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="2")]
    pub conversation_i_ds: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetLastMessageResp {
    #[prost(map="string, message", tag="1")]
    pub msgs: ::std::collections::HashMap<::prost::alloc::string::String, super::sdkws::MsgData>,
}
// @@protoc_insertion_point(module)
