// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetAdminTokenReq {
    #[prost(string, tag="1")]
    pub secret: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub user_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetAdminTokenResp {
    #[prost(string, tag="2")]
    pub token: ::prost::alloc::string::String,
    #[prost(int64, tag="3")]
    pub expire_time_seconds: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ForceLogoutReq {
    #[prost(int32, tag="1")]
    pub platform_id: i32,
    #[prost(string, tag="2")]
    pub user_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ForceLogoutResp {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ParseTokenReq {
    #[prost(string, tag="1")]
    pub token: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ParseTokenResp {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(int32, tag="2")]
    pub platform_id: i32,
    #[prost(int64, tag="4")]
    pub expire_time_seconds: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetUserTokenReq {
    #[prost(int32, tag="1")]
    pub platform_id: i32,
    #[prost(string, tag="2")]
    pub user_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetUserTokenResp {
    #[prost(string, tag="1")]
    pub token: ::prost::alloc::string::String,
    #[prost(int64, tag="2")]
    pub expire_time_seconds: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InvalidateTokenReq {
    #[prost(string, tag="1")]
    pub preserved_token: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(int32, tag="3")]
    pub platform_id: i32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct InvalidateTokenResp {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct KickTokensReq {
    #[prost(string, repeated, tag="1")]
    pub tokens: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct KickTokensResp {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetExistingTokenReq {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(int32, tag="2")]
    pub platform_id: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetExistingTokenResp {
    #[prost(map="string, int32", tag="1")]
    pub token_states: ::std::collections::HashMap<::prost::alloc::string::String, i32>,
}
// @@protoc_insertion_point(module)
