// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ErrorInfo {
    #[prost(string, tag="1")]
    pub path: ::prost::alloc::string::String,
    #[prost(uint32, tag="2")]
    pub line: u32,
    #[prost(string, tag="3")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub cause: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="5")]
    pub warp: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
// @@protoc_insertion_point(module)
