// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ParticipantMetaData {
    #[prost(message, optional, tag="1")]
    pub group_info: ::core::option::Option<super::sdkws::GroupInfo>,
    #[prost(message, optional, tag="2")]
    pub group_member_info: ::core::option::Option<super::sdkws::GroupMemberFullInfo>,
    #[prost(message, optional, tag="3")]
    pub user_info: ::core::option::Option<super::sdkws::PublicUserInfo>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetJoinTokenReq {
    #[prost(string, tag="1")]
    pub room: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub identity: ::prost::alloc::string::String,
    #[prost(message, optional, tag="3")]
    pub meta_data: ::core::option::Option<ParticipantMetaData>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetJoinTokenResp {
    #[prost(string, tag="1")]
    pub jwt: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub live_url: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SignalReq {
    #[prost(oneof="signal_req::Payload", tags="1, 2, 3, 4, 5, 6, 7")]
    pub payload: ::core::option::Option<signal_req::Payload>,
}
/// Nested message and enum types in `SignalReq`.
pub mod signal_req {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Payload {
        #[prost(message, tag="1")]
        Invite(super::SignalInviteReq),
        #[prost(message, tag="2")]
        InviteInGroup(super::SignalInviteInGroupReq),
        #[prost(message, tag="3")]
        Cancel(super::SignalCancelReq),
        #[prost(message, tag="4")]
        Accept(super::SignalAcceptReq),
        #[prost(message, tag="5")]
        HungUp(super::SignalHungUpReq),
        #[prost(message, tag="6")]
        Reject(super::SignalRejectReq),
        #[prost(message, tag="7")]
        GetTokenByRoomId(super::SignalGetTokenByRoomIdReq),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SignalSendCustomSignalReq {
    #[prost(string, tag="1")]
    pub room_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub custom_info: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SignalSendCustomSignalResp {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SignalOnStreamChangeReq {
    #[prost(string, tag="1")]
    pub room_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub stream_type: ::prost::alloc::string::String,
    #[prost(bool, tag="3")]
    pub mute: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SignalResp {
    #[prost(oneof="signal_resp::Payload", tags="1, 2, 3, 4, 5, 6, 7")]
    pub payload: ::core::option::Option<signal_resp::Payload>,
}
/// Nested message and enum types in `SignalResp`.
pub mod signal_resp {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Payload {
        #[prost(message, tag="1")]
        Invite(super::SignalInviteResp),
        #[prost(message, tag="2")]
        InviteInGroup(super::SignalInviteInGroupResp),
        #[prost(message, tag="3")]
        Cancel(super::SignalCancelResp),
        #[prost(message, tag="4")]
        Accept(super::SignalAcceptResp),
        #[prost(message, tag="5")]
        HungUp(super::SignalHungUpResp),
        #[prost(message, tag="6")]
        Reject(super::SignalRejectResp),
        #[prost(message, tag="7")]
        GetTokenByRoomId(super::SignalGetTokenByRoomIdResp),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InvitationInfo {
    #[prost(string, tag="1")]
    pub inviter_user_id: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="2")]
    pub invitee_user_id_list: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag="3")]
    pub custom_data: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub group_id: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub room_id: ::prost::alloc::string::String,
    #[prost(int32, tag="6")]
    pub timeout: i32,
    #[prost(string, tag="7")]
    pub media_type: ::prost::alloc::string::String,
    #[prost(int32, tag="8")]
    pub platform_id: i32,
    #[prost(int32, tag="9")]
    pub session_type: i32,
    #[prost(int64, tag="10")]
    pub initiate_time: i64,
    #[prost(string, repeated, tag="11")]
    pub busy_line_user_id_list: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SignalInviteReq {
    #[prost(message, optional, tag="1")]
    pub invitation: ::core::option::Option<InvitationInfo>,
    #[prost(message, optional, tag="2")]
    pub offline_push_info: ::core::option::Option<super::sdkws::OfflinePushInfo>,
    #[prost(message, optional, tag="3")]
    pub participant: ::core::option::Option<ParticipantMetaData>,
    #[prost(string, tag="4")]
    pub user_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SignalInviteResp {
    #[prost(string, tag="1")]
    pub token: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub room_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub live_url: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="4")]
    pub busy_line_user_id_list: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SignalInviteInGroupReq {
    #[prost(message, optional, tag="1")]
    pub invitation: ::core::option::Option<InvitationInfo>,
    #[prost(message, optional, tag="2")]
    pub offline_push_info: ::core::option::Option<super::sdkws::OfflinePushInfo>,
    #[prost(message, optional, tag="3")]
    pub participant: ::core::option::Option<ParticipantMetaData>,
    #[prost(string, tag="4")]
    pub user_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SignalInviteInGroupResp {
    #[prost(string, tag="1")]
    pub token: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub room_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub live_url: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="4")]
    pub busy_line_user_id_list: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SignalCancelReq {
    #[prost(message, optional, tag="1")]
    pub invitation: ::core::option::Option<InvitationInfo>,
    #[prost(message, optional, tag="2")]
    pub offline_push_info: ::core::option::Option<super::sdkws::OfflinePushInfo>,
    #[prost(message, optional, tag="3")]
    pub participant: ::core::option::Option<ParticipantMetaData>,
    #[prost(string, tag="4")]
    pub user_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SignalCancelResp {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SignalAcceptReq {
    #[prost(message, optional, tag="1")]
    pub invitation: ::core::option::Option<InvitationInfo>,
    #[prost(message, optional, tag="2")]
    pub offline_push_info: ::core::option::Option<super::sdkws::OfflinePushInfo>,
    #[prost(message, optional, tag="3")]
    pub participant: ::core::option::Option<ParticipantMetaData>,
    #[prost(int32, tag="4")]
    pub op_user_platform_id: i32,
    #[prost(string, tag="5")]
    pub user_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SignalAcceptResp {
    #[prost(string, tag="1")]
    pub token: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub room_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub live_url: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SignalHungUpReq {
    #[prost(message, optional, tag="1")]
    pub invitation: ::core::option::Option<InvitationInfo>,
    #[prost(message, optional, tag="2")]
    pub offline_push_info: ::core::option::Option<super::sdkws::OfflinePushInfo>,
    #[prost(string, tag="3")]
    pub user_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SignalHungUpResp {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SignalRejectReq {
    #[prost(message, optional, tag="1")]
    pub invitation: ::core::option::Option<InvitationInfo>,
    #[prost(message, optional, tag="2")]
    pub offline_push_info: ::core::option::Option<super::sdkws::OfflinePushInfo>,
    #[prost(message, optional, tag="3")]
    pub participant: ::core::option::Option<ParticipantMetaData>,
    #[prost(int32, tag="4")]
    pub op_user_platform_id: i32,
    #[prost(string, tag="5")]
    pub user_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SignalRejectResp {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SignalGetRoomByGroupIdReq {
    #[prost(string, tag="1")]
    pub group_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SignalGetRoomByGroupIdResp {
    #[prost(message, optional, tag="1")]
    pub invitation: ::core::option::Option<InvitationInfo>,
    #[prost(message, repeated, tag="2")]
    pub participant: ::prost::alloc::vec::Vec<ParticipantMetaData>,
    #[prost(string, tag="3")]
    pub room_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SignalOnRoomParticipantConnectedReq {
    #[prost(message, optional, tag="1")]
    pub invitation: ::core::option::Option<InvitationInfo>,
    #[prost(message, repeated, tag="2")]
    pub participant: ::prost::alloc::vec::Vec<ParticipantMetaData>,
    #[prost(string, tag="3")]
    pub group_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SignalOnRoomParticipantDisconnectedReq {
    #[prost(message, optional, tag="1")]
    pub invitation: ::core::option::Option<InvitationInfo>,
    #[prost(message, repeated, tag="2")]
    pub participant: ::prost::alloc::vec::Vec<ParticipantMetaData>,
    #[prost(string, tag="3")]
    pub group_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SignalGetTokenByRoomIdReq {
    #[prost(string, tag="1")]
    pub room_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag="2")]
    pub participant: ::core::option::Option<ParticipantMetaData>,
    #[prost(string, tag="3")]
    pub user_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SignalGetTokenByRoomIdResp {
    #[prost(string, tag="1")]
    pub token: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub live_url: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SignalMessageAssembleReq {
    #[prost(message, optional, tag="1")]
    pub signal_req: ::core::option::Option<SignalReq>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SignalMessageAssembleResp {
    #[prost(message, optional, tag="1")]
    pub signal_resp: ::core::option::Option<SignalResp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SignalGetRoomsReq {
    #[prost(string, repeated, tag="1")]
    pub room_i_ds: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SignalGetRoomsResp {
    #[prost(message, repeated, tag="1")]
    pub room_list: ::prost::alloc::vec::Vec<SignalGetRoomByGroupIdResp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetSignalInvitationInfoReq {
    #[prost(string, tag="1")]
    pub room_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetSignalInvitationInfoResp {
    #[prost(message, optional, tag="1")]
    pub invitation_info: ::core::option::Option<InvitationInfo>,
    #[prost(message, optional, tag="2")]
    pub offline_push_info: ::core::option::Option<super::sdkws::OfflinePushInfo>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetSignalInvitationInfoStartAppReq {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetSignalInvitationInfoStartAppResp {
    #[prost(message, optional, tag="1")]
    pub invitation: ::core::option::Option<InvitationInfo>,
    #[prost(message, optional, tag="2")]
    pub offline_push_info: ::core::option::Option<super::sdkws::OfflinePushInfo>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SignalUser {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub nickname: ::prost::alloc::string::String,
    #[prost(int32, tag="3")]
    pub status: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SignalRecord {
    #[prost(string, tag="1")]
    pub room_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub s_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub file_name: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub media_type: ::prost::alloc::string::String,
    #[prost(int32, tag="5")]
    pub session_type: i32,
    #[prost(string, tag="6")]
    pub inviter_user_id: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub inviter_user_nickname: ::prost::alloc::string::String,
    #[prost(string, tag="8")]
    pub group_id: ::prost::alloc::string::String,
    #[prost(string, tag="9")]
    pub group_name: ::prost::alloc::string::String,
    #[prost(message, repeated, tag="10")]
    pub inviter_users: ::prost::alloc::vec::Vec<SignalUser>,
    #[prost(int64, tag="11")]
    pub create_time: i64,
    #[prost(int64, tag="12")]
    pub end_time: i64,
    #[prost(string, tag="13")]
    pub size: ::prost::alloc::string::String,
    #[prost(string, tag="14")]
    pub file_url: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FileRecord {
    #[prost(string, tag="1")]
    pub size: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub file_url: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetSignalInvitationRecordsReq {
    #[prost(message, optional, tag="1")]
    pub pagination: ::core::option::Option<super::sdkws::RequestPagination>,
    #[prost(int32, tag="2")]
    pub session_type: i32,
    #[prost(string, tag="3")]
    pub send_id: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub recv_id: ::prost::alloc::string::String,
    #[prost(int64, tag="5")]
    pub start_time: i64,
    #[prost(int64, tag="6")]
    pub end_time: i64,
    #[prost(message, repeated, tag="7")]
    pub joined_users: ::prost::alloc::vec::Vec<super::sdkws::UserInfo>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetSignalInvitationRecordsResp {
    #[prost(int32, tag="1")]
    pub total: i32,
    #[prost(message, repeated, tag="2")]
    pub signal_records: ::prost::alloc::vec::Vec<SignalRecord>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeleteSignalRecordsReq {
    #[prost(string, repeated, tag="1")]
    pub s_i_ds: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct DeleteSignalRecordsResp {
}
// @@protoc_insertion_point(module)
