// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateGroupReq {
    #[prost(string, repeated, tag="1")]
    pub member_user_i_ds: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, optional, tag="2")]
    pub group_info: ::core::option::Option<super::sdkws::GroupInfo>,
    #[prost(string, repeated, tag="3")]
    pub admin_user_i_ds: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// owner
    #[prost(string, tag="4")]
    pub owner_user_id: ::prost::alloc::string::String,
    #[prost(bool, optional, tag="5")]
    pub send_message: ::core::option::Option<bool>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateGroupResp {
    #[prost(message, optional, tag="1")]
    pub group_info: ::core::option::Option<super::sdkws::GroupInfo>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetGroupsInfoReq {
    #[prost(string, repeated, tag="1")]
    pub group_i_ds: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetGroupsInfoResp {
    #[prost(message, repeated, tag="1")]
    pub group_infos: ::prost::alloc::vec::Vec<super::sdkws::GroupInfo>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetGroupInfoReq {
    #[prost(message, optional, tag="1")]
    pub group_info_for_set: ::core::option::Option<super::sdkws::GroupInfoForSet>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SetGroupInfoResp {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetGroupInfoExReq {
    #[prost(string, tag="1")]
    pub group_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag="2")]
    pub group_name: ::core::option::Option<super::protobuf::StringValue>,
    #[prost(message, optional, tag="3")]
    pub notification: ::core::option::Option<super::protobuf::StringValue>,
    #[prost(message, optional, tag="4")]
    pub introduction: ::core::option::Option<super::protobuf::StringValue>,
    #[prost(message, optional, tag="5")]
    pub face_url: ::core::option::Option<super::protobuf::StringValue>,
    #[prost(message, optional, tag="6")]
    pub ex: ::core::option::Option<super::protobuf::StringValue>,
    #[prost(message, optional, tag="7")]
    pub need_verification: ::core::option::Option<super::protobuf::Int32Value>,
    #[prost(message, optional, tag="8")]
    pub look_member_info: ::core::option::Option<super::protobuf::Int32Value>,
    #[prost(message, optional, tag="9")]
    pub apply_member_friend: ::core::option::Option<super::protobuf::Int32Value>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SetGroupInfoExResp {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetGroupApplicationListReq {
    #[prost(message, optional, tag="1")]
    pub pagination: ::core::option::Option<super::sdkws::RequestPagination>,
    /// owner or admin
    #[prost(string, tag="2")]
    pub from_user_id: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="3")]
    pub group_i_ds: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(int32, repeated, tag="4")]
    pub handle_results: ::prost::alloc::vec::Vec<i32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetGroupApplicationListResp {
    #[prost(uint32, tag="1")]
    pub total: u32,
    #[prost(message, repeated, tag="2")]
    pub group_requests: ::prost::alloc::vec::Vec<super::sdkws::GroupRequest>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetGroupApplicationUnhandledCountReq {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(int64, tag="2")]
    pub time: i64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetGroupApplicationUnhandledCountResp {
    #[prost(int64, tag="1")]
    pub count: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetUserReqApplicationListReq {
    #[prost(message, optional, tag="1")]
    pub pagination: ::core::option::Option<super::sdkws::RequestPagination>,
    #[prost(string, tag="2")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="3")]
    pub group_i_ds: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(int32, repeated, tag="4")]
    pub handle_results: ::prost::alloc::vec::Vec<i32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetUserReqApplicationListResp {
    #[prost(uint32, tag="1")]
    pub total: u32,
    #[prost(message, repeated, tag="2")]
    pub group_requests: ::prost::alloc::vec::Vec<super::sdkws::GroupRequest>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetSpecifiedUserGroupRequestInfoReq {
    #[prost(string, tag="1")]
    pub group_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub user_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetSpecifiedUserGroupRequestInfoResp {
    #[prost(uint32, tag="1")]
    pub total: u32,
    #[prost(message, repeated, tag="2")]
    pub group_requests: ::prost::alloc::vec::Vec<super::sdkws::GroupRequest>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TransferGroupOwnerReq {
    #[prost(string, tag="1")]
    pub group_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub old_owner_user_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub new_owner_user_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct TransferGroupOwnerResp {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct JoinGroupReq {
    #[prost(string, tag="1")]
    pub group_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub req_message: ::prost::alloc::string::String,
    #[prost(int32, tag="3")]
    pub join_source: i32,
    #[prost(string, tag="4")]
    pub inviter_user_id: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub ex: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct JoinGroupResp {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GroupApplicationResponseReq {
    #[prost(string, tag="1")]
    pub group_id: ::prost::alloc::string::String,
    ///
    #[prost(string, tag="2")]
    pub from_user_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub handled_msg: ::prost::alloc::string::String,
    #[prost(int32, tag="4")]
    pub handle_result: i32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GroupApplicationResponseResp {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QuitGroupReq {
    #[prost(string, tag="1")]
    pub group_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub user_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct QuitGroupResp {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetGroupMemberListReq {
    #[prost(message, optional, tag="1")]
    pub pagination: ::core::option::Option<super::sdkws::RequestPagination>,
    #[prost(string, tag="2")]
    pub group_id: ::prost::alloc::string::String,
    #[prost(int32, tag="3")]
    pub filter: i32,
    #[prost(string, tag="4")]
    pub keyword: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetGroupMemberListResp {
    #[prost(uint32, tag="1")]
    pub total: u32,
    #[prost(message, repeated, tag="2")]
    pub members: ::prost::alloc::vec::Vec<super::sdkws::GroupMemberFullInfo>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetGroupMembersInfoReq {
    #[prost(string, tag="1")]
    pub group_id: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="2")]
    pub user_i_ds: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetGroupMembersInfoResp {
    #[prost(message, repeated, tag="1")]
    pub members: ::prost::alloc::vec::Vec<super::sdkws::GroupMemberFullInfo>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct KickGroupMemberReq {
    #[prost(string, tag="1")]
    pub group_id: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="2")]
    pub kicked_user_i_ds: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag="3")]
    pub reason: ::prost::alloc::string::String,
    #[prost(bool, optional, tag="4")]
    pub send_message: ::core::option::Option<bool>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct KickGroupMemberResp {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetJoinedGroupListReq {
    #[prost(message, optional, tag="1")]
    pub pagination: ::core::option::Option<super::sdkws::RequestPagination>,
    #[prost(string, tag="2")]
    pub from_user_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetJoinedGroupListResp {
    #[prost(uint32, tag="1")]
    pub total: u32,
    #[prost(message, repeated, tag="2")]
    pub groups: ::prost::alloc::vec::Vec<super::sdkws::GroupInfo>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InviteUserToGroupReq {
    #[prost(string, tag="1")]
    pub group_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub reason: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="3")]
    pub invited_user_i_ds: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(bool, optional, tag="4")]
    pub send_message: ::core::option::Option<bool>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct InviteUserToGroupResp {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetGroupAllMemberReq {
    #[prost(message, optional, tag="1")]
    pub pagination: ::core::option::Option<super::sdkws::RequestPagination>,
    #[prost(string, tag="2")]
    pub group_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetGroupAllMemberResp {
    #[prost(message, repeated, tag="1")]
    pub members: ::prost::alloc::vec::Vec<super::sdkws::GroupMemberFullInfo>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CmsGroup {
    #[prost(message, optional, tag="1")]
    pub group_info: ::core::option::Option<super::sdkws::GroupInfo>,
    #[prost(string, tag="2")]
    pub group_owner_user_name: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub group_owner_user_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetGroupsReq {
    #[prost(message, optional, tag="1")]
    pub pagination: ::core::option::Option<super::sdkws::RequestPagination>,
    #[prost(string, tag="2")]
    pub group_name: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub group_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetGroupsResp {
    #[prost(uint32, tag="1")]
    pub total: u32,
    #[prost(message, repeated, tag="2")]
    pub groups: ::prost::alloc::vec::Vec<CmsGroup>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetGroupMemberReq {
    #[prost(string, tag="1")]
    pub group_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetGroupMembersCmsReq {
    #[prost(message, optional, tag="1")]
    pub pagination: ::core::option::Option<super::sdkws::RequestPagination>,
    #[prost(string, tag="2")]
    pub group_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub user_name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetGroupMembersCmsResp {
    #[prost(uint32, tag="1")]
    pub total: u32,
    #[prost(message, repeated, tag="2")]
    pub members: ::prost::alloc::vec::Vec<super::sdkws::GroupMemberFullInfo>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DismissGroupReq {
    #[prost(string, tag="1")]
    pub group_id: ::prost::alloc::string::String,
    #[prost(bool, tag="2")]
    pub delete_member: bool,
    #[prost(bool, optional, tag="3")]
    pub send_message: ::core::option::Option<bool>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct DismissGroupResp {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MuteGroupMemberReq {
    #[prost(string, tag="1")]
    pub group_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(uint32, tag="3")]
    pub muted_seconds: u32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MuteGroupMemberResp {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CancelMuteGroupMemberReq {
    #[prost(string, tag="1")]
    pub group_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub user_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CancelMuteGroupMemberResp {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MuteGroupReq {
    #[prost(string, tag="1")]
    pub group_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MuteGroupResp {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CancelMuteGroupReq {
    #[prost(string, tag="1")]
    pub group_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CancelMuteGroupResp {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetGroupMemberInfo {
    #[prost(string, tag="1")]
    pub group_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag="3")]
    pub nickname: ::core::option::Option<super::protobuf::StringValue>,
    #[prost(message, optional, tag="4")]
    pub face_url: ::core::option::Option<super::protobuf::StringValue>,
    #[prost(message, optional, tag="5")]
    pub role_level: ::core::option::Option<super::protobuf::Int32Value>,
    #[prost(message, optional, tag="6")]
    pub ex: ::core::option::Option<super::protobuf::StringValue>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetGroupMemberInfoReq {
    #[prost(message, repeated, tag="1")]
    pub members: ::prost::alloc::vec::Vec<SetGroupMemberInfo>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SetGroupMemberInfoResp {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetGroupAbstractInfoReq {
    #[prost(string, repeated, tag="1")]
    pub group_i_ds: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GroupAbstractInfo {
    #[prost(string, tag="1")]
    pub group_id: ::prost::alloc::string::String,
    #[prost(uint32, tag="2")]
    pub group_member_number: u32,
    #[prost(uint64, tag="3")]
    pub group_member_list_hash: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetGroupAbstractInfoResp {
    #[prost(message, repeated, tag="1")]
    pub group_abstract_infos: ::prost::alloc::vec::Vec<GroupAbstractInfo>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetUserInGroupMembersReq {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="2")]
    pub group_i_ds: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetUserInGroupMembersResp {
    #[prost(message, repeated, tag="1")]
    pub members: ::prost::alloc::vec::Vec<super::sdkws::GroupMemberFullInfo>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetGroupMemberUserIDsReq {
    #[prost(string, tag="1")]
    pub group_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetGroupMemberUserIDsResp {
    #[prost(string, repeated, tag="1")]
    pub user_i_ds: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetGroupMemberRoleLevelReq {
    #[prost(string, tag="1")]
    pub group_id: ::prost::alloc::string::String,
    #[prost(int32, repeated, tag="2")]
    pub role_levels: ::prost::alloc::vec::Vec<i32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetGroupMemberRoleLevelResp {
    #[prost(message, repeated, tag="1")]
    pub members: ::prost::alloc::vec::Vec<super::sdkws::GroupMemberFullInfo>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetGroupInfoCacheReq {
    #[prost(string, tag="1")]
    pub group_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetGroupInfoCacheResp {
    #[prost(message, optional, tag="1")]
    pub group_info: ::core::option::Option<super::sdkws::GroupInfo>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetGroupMemberCacheReq {
    #[prost(string, tag="1")]
    pub group_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub group_member_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetGroupMemberCacheResp {
    #[prost(message, optional, tag="1")]
    pub member: ::core::option::Option<super::sdkws::GroupMemberFullInfo>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GroupCreateCountReq {
    #[prost(int64, tag="1")]
    pub start: i64,
    #[prost(int64, tag="2")]
    pub end: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GroupCreateCountResp {
    #[prost(int64, tag="1")]
    pub total: i64,
    #[prost(int64, tag="2")]
    pub before: i64,
    #[prost(map="string, int64", tag="3")]
    pub count: ::std::collections::HashMap<::prost::alloc::string::String, i64>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetGroupUsersReqApplicationListReq {
    #[prost(string, tag="1")]
    pub group_id: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="2")]
    pub user_i_ds: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetGroupUsersReqApplicationListResp {
    #[prost(int64, tag="1")]
    pub total: i64,
    #[prost(message, repeated, tag="2")]
    pub group_requests: ::prost::alloc::vec::Vec<super::sdkws::GroupRequest>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NotificationUserInfoUpdateReq {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag="2")]
    pub old_user_info: ::core::option::Option<super::sdkws::UserInfo>,
    #[prost(message, optional, tag="3")]
    pub new_user_info: ::core::option::Option<super::sdkws::UserInfo>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct NotificationUserInfoUpdateResp {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetIncrementalGroupMemberReq {
    #[prost(string, tag="1")]
    pub group_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub version_id: ::prost::alloc::string::String,
    #[prost(uint64, tag="3")]
    pub version: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetIncrementalGroupMemberResp {
    #[prost(uint64, tag="1")]
    pub version: u64,
    #[prost(string, tag="2")]
    pub version_id: ::prost::alloc::string::String,
    #[prost(bool, tag="3")]
    pub full: bool,
    #[prost(string, repeated, tag="4")]
    pub delete: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, repeated, tag="5")]
    pub insert: ::prost::alloc::vec::Vec<super::sdkws::GroupMemberFullInfo>,
    #[prost(message, repeated, tag="6")]
    pub update: ::prost::alloc::vec::Vec<super::sdkws::GroupMemberFullInfo>,
    #[prost(message, optional, tag="7")]
    pub group: ::core::option::Option<super::sdkws::GroupInfo>,
    #[prost(uint64, tag="8")]
    pub sort_version: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetIncrementalJoinGroupReq {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub version_id: ::prost::alloc::string::String,
    #[prost(uint64, tag="3")]
    pub version: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetIncrementalJoinGroupResp {
    #[prost(uint64, tag="1")]
    pub version: u64,
    #[prost(string, tag="2")]
    pub version_id: ::prost::alloc::string::String,
    #[prost(bool, tag="3")]
    pub full: bool,
    #[prost(string, repeated, tag="4")]
    pub delete: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, repeated, tag="5")]
    pub insert: ::prost::alloc::vec::Vec<super::sdkws::GroupInfo>,
    #[prost(message, repeated, tag="6")]
    pub update: ::prost::alloc::vec::Vec<super::sdkws::GroupInfo>,
    #[prost(uint64, tag="7")]
    pub sort_version: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetFullGroupMemberUserIDsReq {
    #[prost(uint64, tag="1")]
    pub id_hash: u64,
    #[prost(string, tag="2")]
    pub group_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetFullGroupMemberUserIDsResp {
    #[prost(uint64, tag="1")]
    pub version: u64,
    #[prost(string, tag="2")]
    pub version_id: ::prost::alloc::string::String,
    #[prost(bool, tag="3")]
    pub equal: bool,
    #[prost(string, repeated, tag="4")]
    pub user_i_ds: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetFullJoinGroupIDsReq {
    #[prost(uint64, tag="1")]
    pub id_hash: u64,
    #[prost(string, tag="2")]
    pub user_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetFullJoinGroupIDsResp {
    #[prost(uint64, tag="1")]
    pub version: u64,
    #[prost(string, tag="2")]
    pub version_id: ::prost::alloc::string::String,
    #[prost(bool, tag="3")]
    pub equal: bool,
    #[prost(string, repeated, tag="4")]
    pub group_i_ds: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BatchGetIncrementalGroupMemberReq {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(message, repeated, tag="2")]
    pub req_list: ::prost::alloc::vec::Vec<GetIncrementalGroupMemberReq>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BatchGetIncrementalGroupMemberResp {
    #[prost(map="string, message", tag="1")]
    pub resp_list: ::std::collections::HashMap<::prost::alloc::string::String, GetIncrementalGroupMemberResp>,
}
// @@protoc_insertion_point(module)
