// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OnlinePushMsgReq {
    #[prost(message, optional, tag="1")]
    pub msg_data: ::core::option::Option<super::sdkws::MsgData>,
    #[prost(string, tag="2")]
    pub push_to_user_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OnlinePushMsgResp {
    #[prost(message, repeated, tag="1")]
    pub resp: ::prost::alloc::vec::Vec<SingleMsgToUserPlatform>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SingleMsgToUserResults {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(message, repeated, tag="2")]
    pub resp: ::prost::alloc::vec::Vec<SingleMsgToUserPlatform>,
    #[prost(bool, tag="3")]
    pub online_push: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OnlineBatchPushOneMsgReq {
    #[prost(message, optional, tag="1")]
    pub msg_data: ::core::option::Option<super::sdkws::MsgData>,
    #[prost(string, repeated, tag="2")]
    pub push_to_user_i_ds: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OnlineBatchPushOneMsgResp {
    #[prost(message, repeated, tag="1")]
    pub single_push_result: ::prost::alloc::vec::Vec<SingleMsgToUserResults>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SingleMsgToUserPlatform {
    #[prost(int64, tag="1")]
    pub result_code: i64,
    #[prost(string, tag="2")]
    pub recv_id: ::prost::alloc::string::String,
    #[prost(int32, tag="3")]
    pub recv_plat_form_id: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetUsersOnlineStatusReq {
    #[prost(string, repeated, tag="1")]
    pub user_i_ds: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetUsersOnlineStatusResp {
    #[prost(message, repeated, tag="1")]
    pub success_result: ::prost::alloc::vec::Vec<get_users_online_status_resp::SuccessResult>,
    #[prost(message, repeated, tag="2")]
    pub failed_result: ::prost::alloc::vec::Vec<get_users_online_status_resp::FailedDetail>,
}
/// Nested message and enum types in `GetUsersOnlineStatusResp`.
pub mod get_users_online_status_resp {
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct SuccessDetail {
        #[prost(int32, tag="1")]
        pub platform_id: i32,
        #[prost(string, tag="2")]
        pub conn_id: ::prost::alloc::string::String,
        #[prost(bool, tag="3")]
        pub is_background: bool,
        #[prost(string, tag="4")]
        pub token: ::prost::alloc::string::String,
    }
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct FailedDetail {
        #[prost(string, tag="1")]
        pub user_id: ::prost::alloc::string::String,
    }
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct SuccessResult {
        #[prost(string, tag="1")]
        pub user_id: ::prost::alloc::string::String,
        #[prost(int32, tag="2")]
        pub status: i32,
        #[prost(message, repeated, tag="3")]
        pub detail_platform_status: ::prost::alloc::vec::Vec<SuccessDetail>,
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SingleDetail {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(int32, tag="2")]
    pub status: i32,
    #[prost(message, repeated, tag="3")]
    pub single_platform_token: ::prost::alloc::vec::Vec<SinglePlatformToken>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SinglePlatformToken {
    #[prost(int32, tag="1")]
    pub platform_id: i32,
    #[prost(int32, tag="2")]
    pub total: i32,
    #[prost(string, repeated, tag="3")]
    pub token: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct KickUserOfflineReq {
    #[prost(int32, tag="1")]
    pub platform_id: i32,
    #[prost(string, repeated, tag="2")]
    pub kick_user_id_list: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct KickUserOfflineResp {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MultiTerminalLoginCheckReq {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(int32, tag="2")]
    pub platform_id: i32,
    #[prost(string, tag="3")]
    pub token: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MultiTerminalLoginCheckResp {
}
// @@protoc_insertion_point(module)
