// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConversationMsg {
    #[prost(message, optional, tag="1")]
    pub conversation: ::core::option::Option<super::conversation::Conversation>,
    #[prost(message, optional, tag="2")]
    pub last_msg: ::core::option::Option<super::sdkws::MsgData>,
    #[prost(message, optional, tag="3")]
    pub user: ::core::option::Option<super::sdkws::UserInfo>,
    #[prost(message, optional, tag="4")]
    pub friend: ::core::option::Option<super::relation::FriendInfoOnly>,
    #[prost(message, optional, tag="5")]
    pub group: ::core::option::Option<super::sdkws::GroupInfo>,
    #[prost(int64, tag="6")]
    pub max_seq: i64,
    #[prost(int64, tag="7")]
    pub read_seq: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetActiveConversationsReq {
    #[prost(string, tag="1")]
    pub owner_user_id: ::prost::alloc::string::String,
    #[prost(int64, tag="2")]
    pub count: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetActiveConversationsResp {
    #[prost(int64, tag="1")]
    pub unread_count: i64,
    #[prost(message, repeated, tag="2")]
    pub conversations: ::prost::alloc::vec::Vec<ConversationMsg>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetConversationsReq {
    #[prost(string, tag="1")]
    pub owner_user_id: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="2")]
    pub conversation_i_ds: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetConversationsResp {
    #[prost(int64, tag="1")]
    pub unread_count: i64,
    #[prost(message, repeated, tag="2")]
    pub conversations: ::prost::alloc::vec::Vec<ConversationMsg>,
}
// @@protoc_insertion_point(module)
