// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct KeyValues {
    #[prost(string, tag="1")]
    pub key: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="2")]
    pub values: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SignPart {
    #[prost(int32, tag="1")]
    pub part_number: i32,
    #[prost(string, tag="2")]
    pub url: ::prost::alloc::string::String,
    #[prost(message, repeated, tag="3")]
    pub query: ::prost::alloc::vec::Vec<KeyValues>,
    #[prost(message, repeated, tag="4")]
    pub header: ::prost::alloc::vec::Vec<KeyValues>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AuthSignParts {
    #[prost(string, tag="1")]
    pub url: ::prost::alloc::string::String,
    #[prost(message, repeated, tag="2")]
    pub query: ::prost::alloc::vec::Vec<KeyValues>,
    #[prost(message, repeated, tag="3")]
    pub header: ::prost::alloc::vec::Vec<KeyValues>,
    #[prost(message, repeated, tag="4")]
    pub parts: ::prost::alloc::vec::Vec<SignPart>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PartLimitReq {
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PartLimitResp {
    #[prost(int64, tag="1")]
    pub min_part_size: i64,
    #[prost(int64, tag="2")]
    pub max_part_size: i64,
    #[prost(int32, tag="3")]
    pub max_num_size: i32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PartSizeReq {
    #[prost(int64, tag="1")]
    pub size: i64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PartSizeResp {
    #[prost(int64, tag="2")]
    pub size: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InitiateMultipartUploadReq {
    #[prost(string, tag="1")]
    pub hash: ::prost::alloc::string::String,
    #[prost(int64, tag="2")]
    pub size: i64,
    #[prost(int64, tag="3")]
    pub part_size: i64,
    #[prost(int32, tag="4")]
    pub max_parts: i32,
    #[prost(string, tag="5")]
    pub cause: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub content_type: ::prost::alloc::string::String,
    #[prost(string, tag="8")]
    pub url_prefix: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UploadInfo {
    #[prost(string, tag="1")]
    pub upload_id: ::prost::alloc::string::String,
    #[prost(int64, tag="2")]
    pub part_size: i64,
    #[prost(message, optional, tag="3")]
    pub sign: ::core::option::Option<AuthSignParts>,
    #[prost(int64, tag="4")]
    pub expire_time: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InitiateMultipartUploadResp {
    #[prost(string, tag="1")]
    pub url: ::prost::alloc::string::String,
    #[prost(message, optional, tag="2")]
    pub upload: ::core::option::Option<UploadInfo>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AuthSignReq {
    #[prost(string, tag="1")]
    pub upload_id: ::prost::alloc::string::String,
    #[prost(int32, repeated, tag="2")]
    pub part_numbers: ::prost::alloc::vec::Vec<i32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AuthSignResp {
    #[prost(string, tag="1")]
    pub url: ::prost::alloc::string::String,
    #[prost(message, repeated, tag="2")]
    pub query: ::prost::alloc::vec::Vec<KeyValues>,
    #[prost(message, repeated, tag="3")]
    pub header: ::prost::alloc::vec::Vec<KeyValues>,
    #[prost(message, repeated, tag="4")]
    pub parts: ::prost::alloc::vec::Vec<SignPart>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CompleteMultipartUploadReq {
    #[prost(string, tag="1")]
    pub upload_id: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="2")]
    pub parts: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag="3")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub content_type: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub cause: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub url_prefix: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CompleteMultipartUploadResp {
    #[prost(string, tag="1")]
    pub url: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AccessUrlReq {
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
    #[prost(map="string, string", tag="2")]
    pub query: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AccessUrlResp {
    #[prost(string, tag="1")]
    pub url: ::prost::alloc::string::String,
    #[prost(int64, tag="2")]
    pub expire_time: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InitiateFormDataReq {
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
    #[prost(int64, tag="2")]
    pub size: i64,
    #[prost(string, tag="3")]
    pub content_type: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub group: ::prost::alloc::string::String,
    #[prost(int64, tag="5")]
    pub millisecond: i64,
    #[prost(bool, tag="6")]
    pub absolute: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InitiateFormDataResp {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub url: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub file: ::prost::alloc::string::String,
    #[prost(message, repeated, tag="4")]
    pub header: ::prost::alloc::vec::Vec<KeyValues>,
    #[prost(map="string, string", tag="5")]
    pub form_data: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
    #[prost(int64, tag="6")]
    pub expires: i64,
    #[prost(int32, repeated, tag="7")]
    pub success_codes: ::prost::alloc::vec::Vec<i32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CompleteFormDataReq {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub url_prefix: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CompleteFormDataResp {
    #[prost(string, tag="1")]
    pub url: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeleteOutdatedDataReq {
    #[prost(int64, tag="1")]
    pub expire_time: i64,
    #[prost(string, repeated, tag="2")]
    pub object_group: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(int32, tag="3")]
    pub limit: i32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct DeleteOutdatedDataResp {
    #[prost(int32, tag="1")]
    pub count: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FcmUpdateTokenReq {
    #[prost(int32, tag="1")]
    pub platform_id: i32,
    #[prost(string, tag="2")]
    pub fcm_token: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub account: ::prost::alloc::string::String,
    #[prost(int64, tag="4")]
    pub expire_time: i64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct FcmUpdateTokenResp {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetAppBadgeReq {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(int32, tag="2")]
    pub app_unread_count: i32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SetAppBadgeResp {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FileUrl {
    #[prost(string, tag="1")]
    pub filename: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub url: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UploadLogsReq {
    #[prost(int32, tag="1")]
    pub platform: i32,
    #[prost(message, repeated, tag="2")]
    pub file_ur_ls: ::prost::alloc::vec::Vec<FileUrl>,
    #[prost(string, tag="3")]
    pub app_framework: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub version: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub ex: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct UploadLogsResp {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeleteLogsReq {
    #[prost(string, repeated, tag="1")]
    pub log_i_ds: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct DeleteLogsResp {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SearchLogsReq {
    #[prost(string, tag="1")]
    pub keyword: ::prost::alloc::string::String,
    #[prost(int64, tag="2")]
    pub start_time: i64,
    #[prost(int64, tag="3")]
    pub end_time: i64,
    #[prost(message, optional, tag="4")]
    pub pagination: ::core::option::Option<super::sdkws::RequestPagination>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LogInfo {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub platform: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub url: ::prost::alloc::string::String,
    #[prost(int64, tag="4")]
    pub create_time: i64,
    #[prost(string, tag="5")]
    pub nickname: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub log_id: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub filename: ::prost::alloc::string::String,
    #[prost(string, tag="8")]
    pub system_type: ::prost::alloc::string::String,
    #[prost(string, tag="9")]
    pub ex: ::prost::alloc::string::String,
    #[prost(string, tag="10")]
    pub version: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SearchLogsResp {
    #[prost(message, repeated, tag="1")]
    pub logs_infos: ::prost::alloc::vec::Vec<LogInfo>,
    #[prost(uint32, tag="2")]
    pub total: u32,
}
// @@protoc_insertion_point(module)
