// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Conversation {
    #[prost(string, tag="1")]
    pub owner_user_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub conversation_id: ::prost::alloc::string::String,
    #[prost(int32, tag="3")]
    pub recv_msg_opt: i32,
    #[prost(int32, tag="4")]
    pub conversation_type: i32,
    #[prost(string, tag="5")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub group_id: ::prost::alloc::string::String,
    #[prost(bool, tag="7")]
    pub is_pinned: bool,
    #[prost(string, tag="8")]
    pub attached_info: ::prost::alloc::string::String,
    #[prost(bool, tag="9")]
    pub is_private_chat: bool,
    #[prost(int32, tag="10")]
    pub group_at_type: i32,
    #[prost(string, tag="11")]
    pub ex: ::prost::alloc::string::String,
    #[prost(int32, tag="12")]
    pub burn_duration: i32,
    #[prost(int64, tag="13")]
    pub min_seq: i64,
    #[prost(int64, tag="14")]
    pub max_seq: i64,
    #[prost(int64, tag="15")]
    pub msg_destruct_time: i64,
    #[prost(int64, tag="16")]
    pub latest_msg_destruct_time: i64,
    #[prost(bool, tag="17")]
    pub is_msg_destruct: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConversationReq {
    #[prost(string, tag="1")]
    pub conversation_id: ::prost::alloc::string::String,
    #[prost(int32, tag="2")]
    pub conversation_type: i32,
    #[prost(string, tag="3")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub group_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag="5")]
    pub recv_msg_opt: ::core::option::Option<super::protobuf::Int32Value>,
    #[prost(message, optional, tag="6")]
    pub is_pinned: ::core::option::Option<super::protobuf::BoolValue>,
    #[prost(message, optional, tag="7")]
    pub attached_info: ::core::option::Option<super::protobuf::StringValue>,
    #[prost(message, optional, tag="8")]
    pub is_private_chat: ::core::option::Option<super::protobuf::BoolValue>,
    #[prost(message, optional, tag="9")]
    pub ex: ::core::option::Option<super::protobuf::StringValue>,
    #[prost(message, optional, tag="10")]
    pub burn_duration: ::core::option::Option<super::protobuf::Int32Value>,
    #[prost(message, optional, tag="11")]
    pub min_seq: ::core::option::Option<super::protobuf::Int64Value>,
    #[prost(message, optional, tag="12")]
    pub max_seq: ::core::option::Option<super::protobuf::Int64Value>,
    #[prost(message, optional, tag="13")]
    pub group_at_type: ::core::option::Option<super::protobuf::Int32Value>,
    #[prost(message, optional, tag="14")]
    pub msg_destruct_time: ::core::option::Option<super::protobuf::Int64Value>,
    #[prost(message, optional, tag="15")]
    pub is_msg_destruct: ::core::option::Option<super::protobuf::BoolValue>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetConversationReq {
    #[prost(message, optional, tag="1")]
    pub conversation: ::core::option::Option<Conversation>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SetConversationResp {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetConversationReq {
    #[prost(string, tag="1")]
    pub conversation_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub owner_user_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetConversationResp {
    #[prost(message, optional, tag="2")]
    pub conversation: ::core::option::Option<Conversation>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetSortedConversationListReq {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="2")]
    pub conversation_i_ds: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, optional, tag="3")]
    pub pagination: ::core::option::Option<super::sdkws::RequestPagination>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetSortedConversationListResp {
    #[prost(int64, tag="1")]
    pub conversation_total: i64,
    #[prost(int64, tag="2")]
    pub unread_total: i64,
    #[prost(message, repeated, tag="3")]
    pub conversation_elems: ::prost::alloc::vec::Vec<ConversationElem>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConversationElem {
    #[prost(string, tag="1")]
    pub conversation_id: ::prost::alloc::string::String,
    #[prost(int32, tag="2")]
    pub recv_msg_opt: i32,
    #[prost(int64, tag="3")]
    pub unread_count: i64,
    #[prost(bool, tag="4")]
    pub is_pinned: bool,
    #[prost(message, optional, tag="5")]
    pub msg_info: ::core::option::Option<MsgInfo>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgInfo {
    #[prost(string, tag="1")]
    pub server_msg_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub client_msg_id: ::prost::alloc::string::String,
    #[prost(int32, tag="3")]
    pub session_type: i32,
    #[prost(string, tag="4")]
    pub send_id: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub recv_id: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub sender_name: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub face_url: ::prost::alloc::string::String,
    #[prost(string, tag="8")]
    pub group_id: ::prost::alloc::string::String,
    #[prost(string, tag="9")]
    pub group_name: ::prost::alloc::string::String,
    #[prost(string, tag="10")]
    pub group_face_url: ::prost::alloc::string::String,
    #[prost(int32, tag="11")]
    pub group_type: i32,
    #[prost(uint32, tag="12")]
    pub group_member_count: u32,
    #[prost(int64, tag="13")]
    pub latest_msg_recv_time: i64,
    #[prost(int32, tag="14")]
    pub msg_from: i32,
    #[prost(int32, tag="15")]
    pub content_type: i32,
    #[prost(string, tag="16")]
    pub content: ::prost::alloc::string::String,
    #[prost(string, tag="17")]
    pub ex: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetConversationsReq {
    #[prost(string, tag="1")]
    pub owner_user_id: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="2")]
    pub conversation_i_ds: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetConversationsResp {
    #[prost(message, repeated, tag="2")]
    pub conversations: ::prost::alloc::vec::Vec<Conversation>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetAllConversationsReq {
    #[prost(string, tag="1")]
    pub owner_user_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetAllConversationsResp {
    #[prost(message, repeated, tag="2")]
    pub conversations: ::prost::alloc::vec::Vec<Conversation>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetRecvMsgNotNotifyUserIDsReq {
    #[prost(string, tag="1")]
    pub group_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetRecvMsgNotNotifyUserIDsResp {
    #[prost(string, repeated, tag="1")]
    pub user_i_ds: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateSingleChatConversationsReq {
    #[prost(string, tag="1")]
    pub recv_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub send_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub conversation_id: ::prost::alloc::string::String,
    #[prost(int32, tag="4")]
    pub conversation_type: i32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CreateSingleChatConversationsResp {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateGroupChatConversationsReq {
    #[prost(string, repeated, tag="1")]
    pub user_i_ds: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag="2")]
    pub group_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CreateGroupChatConversationsResp {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetConversationMaxSeqReq {
    #[prost(string, tag="1")]
    pub conversation_id: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="2")]
    pub owner_user_id: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(int64, tag="3")]
    pub max_seq: i64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SetConversationMaxSeqResp {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetConversationMinSeqReq {
    #[prost(string, tag="1")]
    pub conversation_id: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="2")]
    pub owner_user_id: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(int64, tag="3")]
    pub min_seq: i64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SetConversationMinSeqResp {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetConversationIDsReq {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetConversationIDsResp {
    #[prost(string, repeated, tag="1")]
    pub conversation_i_ds: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetConversationsReq {
    #[prost(string, repeated, tag="1")]
    pub user_i_ds: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, optional, tag="2")]
    pub conversation: ::core::option::Option<ConversationReq>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SetConversationsResp {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetUserConversationIDsHashReq {
    #[prost(string, tag="1")]
    pub owner_user_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetUserConversationIDsHashResp {
    #[prost(uint64, tag="1")]
    pub hash: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetConversationsByConversationIdReq {
    #[prost(string, repeated, tag="1")]
    pub conversation_i_ds: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetConversationsByConversationIdResp {
    #[prost(message, repeated, tag="1")]
    pub conversations: ::prost::alloc::vec::Vec<Conversation>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetConversationOfflinePushUserIDsReq {
    #[prost(string, tag="1")]
    pub conversation_id: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="2")]
    pub user_i_ds: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetConversationOfflinePushUserIDsResp {
    #[prost(string, repeated, tag="1")]
    pub user_i_ds: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetConversationNotReceiveMessageUserIDsReq {
    #[prost(string, tag="1")]
    pub conversation_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetConversationNotReceiveMessageUserIDsResp {
    #[prost(string, repeated, tag="1")]
    pub user_i_ds: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateConversationReq {
    #[prost(string, tag="1")]
    pub conversation_id: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="2")]
    pub user_i_ds: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, optional, tag="3")]
    pub recv_msg_opt: ::core::option::Option<super::protobuf::Int32Value>,
    #[prost(message, optional, tag="4")]
    pub is_pinned: ::core::option::Option<super::protobuf::BoolValue>,
    #[prost(message, optional, tag="5")]
    pub attached_info: ::core::option::Option<super::protobuf::StringValue>,
    #[prost(message, optional, tag="6")]
    pub is_private_chat: ::core::option::Option<super::protobuf::BoolValue>,
    #[prost(message, optional, tag="7")]
    pub ex: ::core::option::Option<super::protobuf::StringValue>,
    #[prost(message, optional, tag="8")]
    pub burn_duration: ::core::option::Option<super::protobuf::Int32Value>,
    #[prost(message, optional, tag="9")]
    pub min_seq: ::core::option::Option<super::protobuf::Int64Value>,
    #[prost(message, optional, tag="10")]
    pub max_seq: ::core::option::Option<super::protobuf::Int64Value>,
    #[prost(message, optional, tag="11")]
    pub group_at_type: ::core::option::Option<super::protobuf::Int32Value>,
    #[prost(message, optional, tag="12")]
    pub msg_destruct_time: ::core::option::Option<super::protobuf::Int64Value>,
    #[prost(message, optional, tag="13")]
    pub is_msg_destruct: ::core::option::Option<super::protobuf::BoolValue>,
    #[prost(message, optional, tag="14")]
    pub latest_msg_destruct_time: ::core::option::Option<super::protobuf::Int64Value>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct UpdateConversationResp {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetFullOwnerConversationIDsReq {
    #[prost(uint64, tag="1")]
    pub id_hash: u64,
    #[prost(string, tag="2")]
    pub user_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetFullOwnerConversationIDsResp {
    #[prost(uint64, tag="1")]
    pub version: u64,
    #[prost(string, tag="2")]
    pub version_id: ::prost::alloc::string::String,
    #[prost(bool, tag="3")]
    pub equal: bool,
    #[prost(string, repeated, tag="4")]
    pub conversation_i_ds: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetIncrementalConversationReq {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub version_id: ::prost::alloc::string::String,
    #[prost(uint64, tag="3")]
    pub version: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetIncrementalConversationResp {
    #[prost(uint64, tag="1")]
    pub version: u64,
    #[prost(string, tag="2")]
    pub version_id: ::prost::alloc::string::String,
    #[prost(bool, tag="3")]
    pub full: bool,
    #[prost(string, repeated, tag="4")]
    pub delete: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, repeated, tag="5")]
    pub insert: ::prost::alloc::vec::Vec<Conversation>,
    #[prost(message, repeated, tag="6")]
    pub update: ::prost::alloc::vec::Vec<Conversation>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetOwnerConversationReq {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag="2")]
    pub pagination: ::core::option::Option<super::sdkws::RequestPagination>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetOwnerConversationResp {
    #[prost(int64, tag="1")]
    pub total: i64,
    #[prost(message, repeated, tag="2")]
    pub conversations: ::prost::alloc::vec::Vec<Conversation>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetConversationsNeedClearMsgReq {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetConversationsNeedClearMsgResp {
    #[prost(message, repeated, tag="1")]
    pub conversations: ::prost::alloc::vec::Vec<Conversation>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetNotNotifyConversationIDsReq {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetNotNotifyConversationIDsResp {
    #[prost(string, repeated, tag="1")]
    pub conversation_i_ds: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetPinnedConversationIDsReq {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetPinnedConversationIDsResp {
    #[prost(string, repeated, tag="1")]
    pub conversation_i_ds: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ClearUserConversationMsgReq {
    #[prost(int64, tag="1")]
    pub timestamp: i64,
    #[prost(int32, tag="2")]
    pub limit: i32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ClearUserConversationMsgResp {
    #[prost(int32, tag="1")]
    pub count: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateConversationsByUserReq {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag="2")]
    pub ex: ::core::option::Option<super::protobuf::StringValue>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct UpdateConversationsByUserResp {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeleteConversationsReq {
    #[prost(string, tag="1")]
    pub owner_user_id: ::prost::alloc::string::String,
    #[prost(int64, tag="2")]
    pub need_delete_time: i64,
    /// optional
    #[prost(string, repeated, tag="3")]
    pub conversation_i_ds: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct DeleteConversationsResp {
}
// @@protoc_insertion_point(module)
