// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PushMsgReq {
    #[prost(message, optional, tag="1")]
    pub msg_data: ::core::option::Option<super::sdkws::MsgData>,
    #[prost(string, tag="2")]
    pub conversation_id: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="3")]
    pub user_i_ds: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PushMsgResp {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DelUserPushTokenReq {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(int32, tag="2")]
    pub platform_id: i32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct DelUserPushTokenResp {
}
// @@protoc_insertion_point(module)
