// @generated
// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetAllUserIdReq {
    #[prost(message, optional, tag="1")]
    pub pagination: ::core::option::Option<super::sdkws::RequestPagination>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetAllUserIdResp {
    #[prost(int32, tag="1")]
    pub total: i32,
    #[prost(string, repeated, tag="2")]
    pub user_i_ds: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AccountCheckReq {
    #[prost(string, repeated, tag="1")]
    pub check_user_i_ds: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AccountCheckResp {
    #[prost(message, repeated, tag="1")]
    pub results: ::prost::alloc::vec::Vec<account_check_resp::SingleUserStatus>,
}
/// Nested message and enum types in `accountCheckResp`.
pub mod account_check_resp {
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct SingleUserStatus {
        #[prost(string, tag="1")]
        pub user_id: ::prost::alloc::string::String,
        #[prost(int32, tag="2")]
        pub account_status: i32,
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetDesignateUsersReq {
    #[prost(string, repeated, tag="1")]
    pub user_i_ds: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetDesignateUsersResp {
    #[prost(message, repeated, tag="1")]
    pub users_info: ::prost::alloc::vec::Vec<super::sdkws::UserInfo>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateUserInfoReq {
    #[prost(message, optional, tag="1")]
    pub user_info: ::core::option::Option<super::sdkws::UserInfo>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct UpdateUserInfoResp {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateUserInfoExReq {
    #[prost(message, optional, tag="1")]
    pub user_info: ::core::option::Option<super::sdkws::UserInfoWithEx>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct UpdateUserInfoExResp {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetGlobalRecvMessageOptReq {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(int32, tag="3")]
    pub global_recv_msg_opt: i32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SetGlobalRecvMessageOptResp {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetConversationReq {
    #[prost(message, optional, tag="1")]
    pub conversation: ::core::option::Option<super::conversation::Conversation>,
    #[prost(int32, tag="2")]
    pub notification_type: i32,
    #[prost(string, tag="3")]
    pub operation_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SetConversationResp {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetRecvMsgOptReq {
    #[prost(string, tag="1")]
    pub owner_user_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub conversation_id: ::prost::alloc::string::String,
    #[prost(int32, tag="3")]
    pub recv_msg_opt: i32,
    #[prost(int32, tag="4")]
    pub notification_type: i32,
    #[prost(string, tag="5")]
    pub operation_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SetRecvMsgOptResp {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetConversationReq {
    #[prost(string, tag="1")]
    pub conversation_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub owner_user_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub operation_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetConversationResp {
    #[prost(message, optional, tag="2")]
    pub conversation: ::core::option::Option<super::conversation::Conversation>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetConversationsReq {
    #[prost(string, tag="1")]
    pub owner_user_id: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="2")]
    pub conversation_i_ds: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag="3")]
    pub operation_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetConversationsResp {
    #[prost(message, repeated, tag="2")]
    pub conversations: ::prost::alloc::vec::Vec<super::conversation::Conversation>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetAllConversationsReq {
    #[prost(string, tag="1")]
    pub owner_user_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub operation_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetAllConversationsResp {
    #[prost(message, repeated, tag="2")]
    pub conversations: ::prost::alloc::vec::Vec<super::conversation::Conversation>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BatchSetConversationsReq {
    #[prost(message, repeated, tag="1")]
    pub conversations: ::prost::alloc::vec::Vec<super::conversation::Conversation>,
    #[prost(string, tag="2")]
    pub owner_user_id: ::prost::alloc::string::String,
    #[prost(int32, tag="3")]
    pub notification_type: i32,
    #[prost(string, tag="4")]
    pub operation_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BatchSetConversationsResp {
    #[prost(string, repeated, tag="2")]
    pub success: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag="3")]
    pub failed: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetPaginationUsersReq {
    #[prost(message, optional, tag="2")]
    pub pagination: ::core::option::Option<super::sdkws::RequestPagination>,
    #[prost(string, tag="3")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub nick_name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetPaginationUsersResp {
    #[prost(int32, tag="1")]
    pub total: i32,
    #[prost(message, repeated, tag="2")]
    pub users: ::prost::alloc::vec::Vec<super::sdkws::UserInfo>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UserRegisterReq {
    #[prost(message, repeated, tag="1")]
    pub users: ::prost::alloc::vec::Vec<super::sdkws::UserInfo>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct UserRegisterResp {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetGlobalRecvMessageOptReq {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetGlobalRecvMessageOptResp {
    #[prost(int32, tag="1")]
    pub global_recv_msg_opt: i32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct UserRegisterCountReq {
    #[prost(int64, tag="1")]
    pub start: i64,
    #[prost(int64, tag="2")]
    pub end: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UserRegisterCountResp {
    #[prost(int64, tag="1")]
    pub total: i64,
    #[prost(int64, tag="2")]
    pub before: i64,
    #[prost(map="string, int64", tag="3")]
    pub count: ::std::collections::HashMap<::prost::alloc::string::String, i64>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SubscribeOrCancelUsersStatusReq {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="2")]
    pub user_i_ds: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(int32, tag="3")]
    pub genre: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SubscribeOrCancelUsersStatusResp {
    #[prost(message, repeated, tag="1")]
    pub status_list: ::prost::alloc::vec::Vec<OnlineStatus>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetSubscribeUsersStatusReq {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetSubscribeUsersStatusResp {
    #[prost(message, repeated, tag="1")]
    pub status_list: ::prost::alloc::vec::Vec<OnlineStatus>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OnlineStatus {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(int32, tag="2")]
    pub status: i32,
    #[prost(int32, repeated, tag="3")]
    pub platform_i_ds: ::prost::alloc::vec::Vec<i32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetUserStatusReq {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="2")]
    pub user_i_ds: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetUserStatusResp {
    #[prost(message, repeated, tag="1")]
    pub status_list: ::prost::alloc::vec::Vec<OnlineStatus>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetUserStatusReq {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(int32, tag="2")]
    pub status: i32,
    #[prost(int32, tag="3")]
    pub platform_id: i32,
    #[prost(string, tag="4")]
    pub conn_id: ::prost::alloc::string::String,
    #[prost(bool, tag="5")]
    pub is_background: bool,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SetUserStatusResp {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UserOnlineStatus {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub conn_id: ::prost::alloc::string::String,
    #[prost(int32, repeated, tag="3")]
    pub online: ::prost::alloc::vec::Vec<i32>,
    #[prost(int32, repeated, tag="4")]
    pub offline: ::prost::alloc::vec::Vec<i32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetUserOnlineStatusReq {
    #[prost(message, repeated, tag="1")]
    pub status: ::prost::alloc::vec::Vec<UserOnlineStatus>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SetUserOnlineStatusResp {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProcessUserCommandAddReq {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(int32, tag="2")]
    pub r#type: i32,
    #[prost(string, tag="3")]
    pub uuid: ::prost::alloc::string::String,
    #[prost(message, optional, tag="4")]
    pub value: ::core::option::Option<super::protobuf::StringValue>,
    #[prost(message, optional, tag="5")]
    pub ex: ::core::option::Option<super::protobuf::StringValue>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ProcessUserCommandAddResp {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProcessUserCommandDeleteReq {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(int32, tag="2")]
    pub r#type: i32,
    #[prost(string, tag="3")]
    pub uuid: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ProcessUserCommandDeleteResp {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProcessUserCommandUpdateReq {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(int32, tag="2")]
    pub r#type: i32,
    #[prost(string, tag="3")]
    pub uuid: ::prost::alloc::string::String,
    #[prost(message, optional, tag="4")]
    pub value: ::core::option::Option<super::protobuf::StringValue>,
    #[prost(message, optional, tag="5")]
    pub ex: ::core::option::Option<super::protobuf::StringValue>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ProcessUserCommandUpdateResp {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProcessUserCommandGetReq {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(int32, tag="2")]
    pub r#type: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CommandInfoResp {
    #[prost(int32, tag="1")]
    pub r#type: i32,
    #[prost(int64, tag="2")]
    pub create_time: i64,
    #[prost(string, tag="3")]
    pub uuid: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub value: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub ex: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProcessUserCommandGetResp {
    #[prost(message, repeated, tag="1")]
    pub command_resp: ::prost::alloc::vec::Vec<CommandInfoResp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProcessUserCommandGetAllReq {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AllCommandInfoResp {
    #[prost(int32, tag="1")]
    pub r#type: i32,
    #[prost(int64, tag="2")]
    pub create_time: i64,
    #[prost(string, tag="3")]
    pub uuid: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub value: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub ex: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProcessUserCommandGetAllResp {
    #[prost(message, repeated, tag="1")]
    pub command_resp: ::prost::alloc::vec::Vec<AllCommandInfoResp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AddNotificationAccountReq {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub nick_name: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub face_url: ::prost::alloc::string::String,
    #[prost(int32, tag="4")]
    pub app_manger_level: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AddNotificationAccountResp {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub face_url: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub nick_name: ::prost::alloc::string::String,
    #[prost(int32, tag="4")]
    pub app_manger_level: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateNotificationAccountInfoReq {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub face_url: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub nick_name: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct UpdateNotificationAccountInfoResp {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SearchNotificationAccountReq {
    #[prost(string, tag="1")]
    pub keyword: ::prost::alloc::string::String,
    #[prost(int32, optional, tag="2")]
    pub app_manager_level: ::core::option::Option<i32>,
    #[prost(message, optional, tag="3")]
    pub pagination: ::core::option::Option<super::sdkws::RequestPagination>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NotificationAccountInfo {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub face_url: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub nick_name: ::prost::alloc::string::String,
    #[prost(int32, tag="4")]
    pub app_manger_level: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SearchNotificationAccountResp {
    #[prost(int64, tag="1")]
    pub total: i64,
    #[prost(message, repeated, tag="2")]
    pub notification_accounts: ::prost::alloc::vec::Vec<NotificationAccountInfo>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetNotificationAccountReq {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetNotificationAccountResp {
    #[prost(message, optional, tag="1")]
    pub account: ::core::option::Option<NotificationAccountInfo>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SortQueryReq {
    #[prost(bool, tag="1")]
    pub asc: bool,
    #[prost(map="string, string", tag="2")]
    pub user_id_name: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SortQueryResp {
    #[prost(message, repeated, tag="2")]
    pub users: ::prost::alloc::vec::Vec<super::sdkws::UserInfo>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetAllOnlineUsersReq {
    #[prost(uint64, tag="1")]
    pub cursor: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetAllOnlineUsersResp {
    #[prost(message, repeated, tag="1")]
    pub status_list: ::prost::alloc::vec::Vec<OnlineStatus>,
    #[prost(uint64, tag="2")]
    pub next_cursor: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetUserClientConfigReq {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetUserClientConfigResp {
    #[prost(map="string, string", tag="2")]
    pub configs: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetUserClientConfigReq {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(map="string, string", tag="2")]
    pub configs: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SetUserClientConfigResp {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DelUserClientConfigReq {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="2")]
    pub keys: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct DelUserClientConfigResp {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PageUserClientConfigReq {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub key: ::prost::alloc::string::String,
    #[prost(message, optional, tag="3")]
    pub pagination: ::core::option::Option<super::sdkws::RequestPagination>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PageUserClientConfigResp {
    #[prost(int64, tag="1")]
    pub total: i64,
    #[prost(message, repeated, tag="2")]
    pub configs: ::prost::alloc::vec::Vec<ClientConfig>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClientConfig {
    #[prost(string, tag="1")]
    pub key: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub value: ::prost::alloc::string::String,
}
// @@protoc_insertion_point(module)
